framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                    redeliver_timeout: 14400
                retry_strategy:
                    max_retries: 5
                    delay: 30000
                    multiplier: 2
                    max_delay: 900000
                    jitter: 0.1

            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\SyncClientMessage: async
            App\Message\SyncProductMessage: async
            App\Message\SyncProductStockMessage: async
            App\Message\SyncInvoiceMessage: async
