parameters:
    base_uri_hubspot: 'https://api.hubapi.com'
    hubspot_portal_id: '143807682'
    hubspot_access: '%env(HUBSPOT_ACCESS_TOKEN)%'
    hubspot_order_form_pipeline_label: 'Pipeline sales'
    hubspot_order_form_pipeline_value: 'default'
    hubspot_order_form_stage_label: 'Sending the offer'
    hubspot_order_form_tax_rate_group_ids:
        '5.5': '115152085'
        '20': '115152086'
    base_uri_sage: '%env(SAGE_BASE_URI)%'
    sage_username: '%env(SAGE_USERNAME)%'
    sage_password: '%env(SAGE_PASSWORD)%'
    mailer_from: 'pro@ultrapop.com'
    erp_order_notification_recipients:
        - 'corentin.bury@lnstrade.fr'
        - 'nikoloz.mamyan@lnstrade.fr'
    order_form_upload_dir: '%kernel.project_dir%/var/uploads/order_forms'
    # sage_client_id: '%env(default::SAGE_CLIENT_ID)%'
    # sage_client_secret: '%env(default::SAGE_CLIENT_SECRET)%'    

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Mailer\SimpleMailerService:
        arguments:
            $defaultFrom: '%mailer_from%'
            $defaultRecipients: '%erp_order_notification_recipients%'
